spring.application.name=test-application

# ===============================
# Server Configuration
# ===============================
server.port=8082
server.servlet.context-path=/java-app

management.endpoints.web.exposure.include=health,info,prometheus

# ===============================
# Logging configuration
# ===============================

logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.demo=DEBUG


# ===============================
# Spring Boot Actuator
# ===============================

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always

management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true
otel.service.name=test-application 
otel.exporter.otlp.endpoint=http://localhost:4317 
otel.exporter.otlp.protocol=grpc