spring.application.name=test

# ===============================
# Logging configuration
# ===============================

logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

# ===============================
# Spring Boot Actuator
# ===============================

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true